### ISSUE TITLE
Back button from CSP causes endless page reloading on detlang.html AB#7153

### ISSUE THREAD

**Issue by vid** [sign-in-canada/Acceptance-Platform#10]
To reproduce: 

Chrome 88 on Linux, non incognito. 

Go to a RP (eg catslab.powerappsportals)
Choose Sign in
Press back button

The detlang.html page constantly reloads.

Could be an extension as it doesn't happen incognito.

**Comment by vid** [comment]
It looks like this Chrome extension is causing the problem: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm/related?hl=en

**Comment by harrdou** [comment]
Bug created: AB#7513

**Comment by harrdou** [comment]
Fixed with 712a29d98c3493ca8592b8e7bdf18dc0c52306a0
