### ISSUE TITLE
Decide on domain structure for development

### ISSUE THREAD

**Issue by MAH005** [sign-in-canada/Acceptance-Platform#110]

**Comment by iamnvc** [comment]
Strategy for DNS?

**Comment by MAH005** [comment]
dev1-ui.id.alpha.canada.ca

**Comment by harrdou** [comment]
That's just a name. There is as yet no strategy.

**Comment by wmoussa-gc** [comment]
we're covering this with https://github.com/orgs/sign-in-canada/projects/5?pane=issue&itemId=20089670
