### ISSUE TITLE
Release SMS MFA and Email Two Step

### ISSUE THREAD

**Issue by stephenyates-gc** [sign-in-canada/Acceptance-Platform#146]
Complete all needed work to release SMS MFA to production.

What is needed?

- [x] ATO
- Document changes for assessment (Zeina)
- Pentest/ vulnerability assessment by Trevor in CATE. 
- Update SA&A artifacts (Zeina)
- Meet with Mario (assessor) to show evidence. Everything that was previously compliant still is. Everything added is compliant.
- Mario is attempting to get us the extension of the current service ATO by March 10. We will attempt to provide enough evidence for him to get us the ATO for the new SMS feature. 
- Other team members could support with documentation (Doug, Emma, Stephen). We will meet to list and assign the needed document changes.
- [x] Privacy impact assessment
- ideally timed with the ATO, but will not hold up the ATO.
- updating with the additional data we are collecting and using, plus added telemetry about user behavior.
- Sherri is the specialist, they are delayed because of a contract issue.

- [ ] Signatures from Katherine and others (CIO, CTO, security assessor, and business owner)
- [ ] Schedule the release, adding the GC Notify key to vault

Completed

- [x] soak in CATE
- [x] bug fixes

**Comment by stephenyates-gc** [comment]
We could release the new build to production but not turn on the MFA additions for any clients.

**Comment by stephenyates-gc** [comment]
on track to release code to production on Sunday.
on track to deliver documentation to assessor next week.

**Comment by wmoussa-gc** [comment]
Code released and waiting to be turned on when the ATO is signed. ETA for the ATO is April 7th.

**Comment by wmoussa-gc** [comment]
SAR going to be completed today, April 3rd. IMTD needs to review it and sign it first..

**Comment by zmatta** [comment]
SAR completion is expected on April 17.

**Comment by wmoussa-gc** [comment]
Live in production.
