### ISSUE TITLE
Renew TLS certificate for CATE

### ISSUE THREAD

**Issue by harrdou** [sign-in-canada/Acceptance-Platform#154]
Certificate will expire April 14.

- [x] Generate new certificate signing request
- [x] Open IMTD Jira ticket and attach CSR
- [x] Convert certificate to PKCS12 format for the F5
- [x] Package the certificate in PEM format for Key Vault
- [x] Update certificate on the F5 and test
- [x] Update the certificate in Key Vault and test

**Comment by MAH005** [comment]
Hey Doug, any news from SSC yet?

**Comment by harrdou** [comment]
Finally got the new cert from SSC this morning. Up to me now to reformat it for IMTD.

**Comment by harrdou** [comment]
New certificate installed and tested. Good until April 2024.
