### ISSUE TITLE
Complete a Baked AMI image

### ISSUE THREAD

**Issue by wmoussa-gc** [sign-in-canada/Acceptance-Platform#158]
work with Mark to get a completed and baked AMI image

- [x] Pipeline for base image

**Comment by paladapustbs** [comment]
should be a change to do that today since we completed and install yesterday with Mark B

**Comment by paladapustbs** [comment]
base pipeline will be completed today 
push GLUU and Database to next sprint

**Comment by wmoussa-gc** [comment]
AWS migration project cancelled.
