### ISSUE TITLE
SPRINT -- 6  Develop AMI Pipeline for Couchbase base image

### ISSUE THREAD

**Issue by paladapustbs** [sign-in-canada/Acceptance-Platform#182]
- [x] 	AWS to create ami pipeline in cdk to deliver hardened couchbase images
- [x] 	AWS testing and security review
- [x] 	Create Base pipeline github repo and transfer code
- [ ] 	Deploy Couchbase AMI Pipeline in DEV

**Comment by paladapustbs** [comment]
mark open PR (Pull Request) for GLUU And CouchBase basic merge

**Comment by wmoussa-gc** [comment]
AWS migration project cancelled.
